### ISSUE TITLE
Groovy scripts don't work

### ISSUE THREAD

**Issue by 1WMAlex** [groovier-minecraft/Groovier#1]
None of the example scripts work on a paper 1.19 server nor a spigot 1.20 server

**Comment by eric2788** [comment]
Hello there, recent I have been kind of busy working, and probably need some time to catch up, i will reply to you for more details when I have time, thanks anyway ☺️

**Comment by eric2788** [comment]
@1WMAlex Hello there, could you provide the details below:
- is there any error appearing in the log? (please provide it if it does)
- what version of Groovier are you using?
- how do you test the scripts?

any thanks

**Comment by eric2788** [comment]
wiki changed and new version released
